# Generated by Django 5.1.1 on 2024-10-25 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='incomeentry',
            name='member',
        ),
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='donation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='donation',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contributor'),
        ),
        migrations.AlterUniqueTogether(
            name='donation',
            unique_together={('contributor', 'charity', 'date')},
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='date_of_donation',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donation_amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='income_entry',
        ),
        migrations.DeleteModel(
            name='IncomeEntry',
        ),
    ]
