# Generated by Django 5.1.1 on 2024-10-25 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contributor_remove_incomeentry_member_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donation',
            unique_together={('contributor', 'amount', 'date')},
        ),
    ]
