# Generated by Django 5.1.1 on 2024-10-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_donation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
